#! /bin/bash
# Contrieved setup to run worker, logger and controllers

TOTIME=40

timeout $TOTIME python worker.py &
timeout $TOTIME python receive_log.py &
sleep 1
python anybodyhome.py
workerOK=$?
if [ "$workerOK" != "0" ]; then 
  echo "Worker not started"
  exit 1
fi
python dowork.py
python sendcmd.py start

sleep $TOTIME