language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: ./SETUP
# command to run tests, e.g. python setup.py test
script:
  - pep8 -r src
  - ./testunit
  - ./testjson2stages
  - ./testbsmx2stages
  - ./threadrecipe
  - ./threadbsmx
  - ./testHWcode
