#!/bin/bash
echo "Unit test..."
./testunit > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Unit Tests Failed !!!!!!!!!!"
    exit 1
fi
echo "Testing web app with selenium..."
./testselenium > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Selenium test failed !!!!!!!!!!"
    exit 1
fi
echo "Recipe test.."
./testrecipe > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Recipe Tests Failed !!!!!!!!!!"
    exit 1
fi
echo "BeerSmith bsmx test.."
./testbsmx > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Recipe Tests Failed !!!!!!!!!!"
    exit 1
fi
echo "Testing HW specific software..."
./testHWcode > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! HW specific code failed !!!!!!!!!!"
    exit 1
fi
echo "Lint (pep8).."
./pepme > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Lint (pepme) Failed !!!!!!!!!!"
    exit 1
fi
echo "Make documentation.."
./mkdocs > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Make documentation Failed !!!!!!!!!!"
    exit 1
fi
echo "=========== Everything is OK! ================"
