#!/bin/bash

echo Pre requirements checks...
#service mosquitto status | grep running
#if [ "$?" != "0" ]; then
#    echo "!!!!!!!!!! Mosquitto must be running !!!!!!!!!!"
#    exit 1
#fi


echo "Unit test..."
./testunit > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Unit Tests Failed !!!!!!!!!!"
    exit 1
fi

echo "bsmx read of equipmentname test, lightweight initial test.."
./testequipmentname > /dev/null 2>&1
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! bsmx read of equipmentname Tests Failed !!!!!!!!!!"
    exit 1
fi

echo "json to stages test.."
./testjson2stages > /dev/null 2>&1
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! json to stages Tests Failed !!!!!!!!!!"
    exit 1
fi
echo "bsmx to stages test.."
./testbsmx2stages > /dev/null 2>&1
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! bsxm to stages Tests Failed !!!!!!!!!!"
    exit 1
fi
echo "Recipe test with thread version.."
./threadrecipe > /dev/null 2>&1
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Thread Recipe Tests Failed !!!!!!!!!!"
    exit 1
fi
echo "Thread BeerSmith bsmx test.."
./threadbsmx > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Thread BeerSmith Tests Failed !!!!!!!!!!"
    exit 1
fi

# This test is fragile and will  never fail
#echo "Testing communication specific code..."
#./testcomm > /dev/null
#if [ "$?" != "0" ]; then
#    echo "!!!!!!!!!! Communication specific code failed !!!!!!!!!!"
#    exit 1
#fi

echo "Testing mqtt based controller using recipe files (json)..."
./testmqttrecipe > /dev/null 2>&1
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Mqtt based controller failed with recipe files (json) !!!!!!!!!!"
    exit 1
fi
echo "Testing mqtt based controller using bsmx files..."
./testmqttbsmx > /dev/null 2>&1
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Mqtt based controller failed with BSMX files !!!!!!!!!!"
    exit 1
fi
echo "Testing HW specific software..."
./testHWcode > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! HW specific code failed !!!!!!!!!!"
    exit 1
fi

# Giving up on pep8 for now.
#echo "Lint (pep8).."
#./pepme > /dev/null
#if [ "$?" != "0" ]; then
#    echo "!!!!!!!!!! Lint (pepme) Failed !!!!!!!!!!"
#    exit 1
#fi

# Not a check, is currently errorprone remove
#echo "Make documentation.."
#./mkdocs > /dev/null
#if [ "$?" != "0" ]; then
#    echo "!!!!!!!!!! Make documentation Failed !!!!!!!!!!"
#    exit 1
#fi

echo "=========== Everything is OK! ================"
