#!/bin/bash
echo "Unit test..."
./testunit > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Unit Tests Failed !!!!!!!!!!"
    exit 1
fi
#echo "Recipe test.."
#./testrecipe > /dev/null
#if [ "$?" != "0" ]; then
#    echo "!!!!!!!!!! Recipe Tests Failed !!!!!!!!!!"
#    exit 1
#fi
#echo "BeerSmith bsmx test.."
#./testbsmx > /dev/null
#if [ "$?" != "0" ]; then
#    echo "!!!!!!!!!! BeerSmith Tests Failed !!!!!!!!!!"
#    exit 1
#fi
echo "json to stages test.."
./testjson2stages > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! json to stages Tests Failed !!!!!!!!!!"
    exit 1
fi
echo "bsmx to stages test.."
./testbsmx2stages > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! bsxm to stages Tests Failed !!!!!!!!!!"
    exit 1
fi
echo "Recipe test with thread version.."
./threadrecipe > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Thread Recipe Tests Failed !!!!!!!!!!"
    exit 1
fi
echo "Thread BeerSmith bsmx test.."
./threadbsmx > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Thread BeerSmith Tests Failed !!!!!!!!!!"
    exit 1
fi
echo "Testing HW specific software..."
./testHWcode > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! HW specific code failed !!!!!!!!!!"
    exit 1
fi
echo "Lint (pep8).."
./pepme > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Lint (pepme) Failed !!!!!!!!!!"
    exit 1
fi
echo "Make documentation.."
./mkdocs > /dev/null
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Make documentation Failed !!!!!!!!!!"
    exit 1
fi
echo "=========== Everything is OK! ================"
