#!/bin/bash

HOMEDIR=`pwd`

sudo apt-get update
sudo apt-get install apache2

sudo apt-get -y install python-setuptools
sudo apt-get -y install g++

# Python packages. May require github downloads
sudo easy_install pyusb
sudo easy_install pyserial
sudo apt-get install pep8
sudo apt-get install python-nose


# Potential futures
#sudo apt-get install memcached
#sudo easy_install python-memcached
#sudo apt-get install python-sqlalchemy


# GoIO
sudo apt-get install pkg-config

cd GoIO-2.28.0
./configure
./configure --prefix=/usr --sysconfdir=/etc
make
sudo make install

cd $HOMEDIR/GoIO-2.28.0/mytemp
make
cd $HOMEDIR

#sudo easy_install python-x10
git clone https://github.com/glibersat/python-x10.git
cd python-x10
sudo python setup.py install
cd $HOMEDIR
rm -rf python-x10

# phidgets
sudo apt-get install libusb-1.0-0-dev

pushd /tmp
wget http://www.phidgets.com/downloads/libraries/libphidget.tar.gz
tar xvzf libphidget.tar.gz
#cd libphidget-2.1.8.20120912
cd libphidget-*
./configure 
make 
sudo make install 
popd

pushd /tmp
wget http://www.phidgets.com/downloads/libraries/PhidgetsPython.zip
unzip PhidgetsPython.zip
cd PhidgetsPython/
sudo python setup.py install
popd

#Pololu, servo USB controller
sudo apt-get install libusb-1.0-0-dev mono-gmcs mono-devel libmono-winforms2.0-cil
cd /tmp
wget http://www.pololu.com/file/download/pololu-usb-sdk-120712.zip?file_id=0J568
unzip pololu-usb-sdk-120712.zip
cd pololu-usb-sdk
# Avoid sudo requirement to access USB port
sudo cp 99-pololu.rules /etc/udev/rules.d/

# Everything is compiled for x86 so you could skip the below two lines
make clean
make
cp Maestro/UscCmd $HOMEDIR

cd $HOMEDIR/src
cd cgibin
sudo ./INSTALL

cd $HOMEDIR
./checkall



