#!/bin/bash

HOMEDIR=`pwd`

sudo apt-get -y install python-setuptools
sudo apt-get -y install g++

# Python packages. May require github downloads
sudo easy_install pyusb
sudo easy_install pyserial

# GoIO
cd GoIO-2.28.0
./configure
./INSTALL

cd $HOMEDIR/GoIO-2.28.0/mytemp
make
cd $HOMEDIR

#sudo easy_install python-x10
git clone https://github.com/glibersat/python-x10.git
cd python-x10
sudo python setup.py install
cd $HOMEDIR
rm -rf python-x10

sudo apt-get install python-nose

sudo apt-get install apache2
cd $HOMEDIR
cd cgi-bin
sudo ./INSTALL

cd $HOMEDIR
./testme



