#!/bin/bash
pushd src/bottle-selenium &>/dev/null
nosetests $1 
if [ "$?" != "0" ]; then
    echo "!!!!!!!!!! Tests Failed !!!!!!!!!!"
    popd &>/dev/null
    exit 1
fi

echo "===========All Tests Passed================"
popd &>/dev/null
