#!/bin/bash

# Goes through all the the recipe in the recipe folder
# Runs the controller in quick mode
# Fails on first failing recipe


pushd recipe  &> /dev/null
for recipe in *; do
  ../src/recipemqtt.sh -q -f $recipe  &> /dev/null
  if [ "$?" != "0" ] ; then
    echo recipe
    echo "!!!!!!!!!! Tests Failed !!!!!!!!!!"
    exit 1
  fi
done
popd
echo "===========All Tests Passed================"
