#! /bin/bash
#
# This script will test the hardware specific code required.
# The test is to check that the installation is OK
# The code is typically compiled C code.
# Note that it will NOT test the hardware just that the software execs
# required are working.

lsusb
if [ "$?" != "0" ]; then
  echo "HW USB not present, exit gracefully"
  exit 0
fi

UscCmd/UscCmd --list
if [ "$?" != "0" ]; then echo "Error: UscCmd not working"; exit 1; fi

GoIO-2.28.0/mytemp/mytemp
if [ "$?" != "0" ]; then echo "Error: GoIO not working"; exit 1; fi



echo "All hardware specific code is working"