#! /bin/bash
#
# This script will test the hardware specific code required.
# The test is to check that the installation is OK
# The code is typically compiled C code.
# Note that it will NOT test the hardware just that the software execs
# required are working.

#Check that the C-code executables are compiled
if [ ! -x ./boilerValve/boilerValve ]; then echo "boilerValve missing"; exit 1; fi
if [ ! -x ./coolerUSB/coolerUSB ]; then echo "coolerUSB missing"; exit 1; fi
if [ ! -x ./mashStirUSB/mashStirUSB ]; then echo "mashStirUSB missing"; exit 1; fi
if [ ! -x ./UscCmd/UscCmd ]; then echo "UscCmd missing"; exit 1; fi

lsusb
if [ "$?" != "0" ]; then
  echo "HW USB not present, exit gracefully"
  exit 0
fi

UscCmd/UscCmd --list
if [ "$?" != "0" ]; then echo "Error: UscCmd not working"; exit 1; fi


echo "All hardware specific code is working"
