#! /bin/bash
#
# This script will test the hardware specific code required.
# The test is to check that the installation is OK
# The code is typically compiled C code.
# Note that it will NOT test the hardware just that the software execs
# required are working.

UscCmd/UscCmd --list
if [ "$?" != "0" ]; then echo "Error: UscCmd not working"; exit 1; fi

GoIO-2.28.0/mytemp/mytemp
if [ "$?" != "0" ]; then echo "Error: GoIO not working"; exit 1; fi

DigiWeight/usbscale
if [ "$?" == "0" ] || [ "$?" == "1" ]; then 
  echo DigiScale OK
else
  echo "Error: DigiScale not working"
  exit 1
fi


echo "All hardware specific code is working"