#!/bin/bash

# Goes through all the the recipe in the recipe folder
# Runs the controller in quick mode
# Fails on first failing recipe

echo "Requires mosquitto running locally"

pushd recipe
for recipe in *; do
  echo ".......................$recipe"
  python ../src/runmqtt.py -m -q -f $recipe
  if [ "$?" != "0" ] ; then
    echo "!!!!!!!!!! Tests Failed !!!!!!!!!!"
    echo "Is mosquitto running locally ?"
    exit 1
  fi
done
popd
echo "===========All Tests Passed================"
