#!/bin/bash

# Goes through all the the recipe in the recipe folder
# Runs the controller in quick mode
# Fails on first failing recipe


pushd beersmith
for recipe in *; do
  echo ".......................$recipe"
  equipment=$(python ../src/bsmx2equipmentname.py -i $recipe)
  python ../src/runmqtt.py -n -q -b $recipe -t "$equipment"
  if [ "$?" != "0" ] ; then
    echo "!!!!!!!!!! Tests Failed !!!!!!!!!!"
    exit 1
  fi
done
popd
echo "===========All Tests Passed================"
