#!/bin/bash
FAIL=0
for bsmx in beersmith/*
do
  echo -n "."
  fbname=$(basename "$bsmx" .bsmx)
  tstfile="bsmxStages/$fbname.tmp"
  goldfile="bsmxStages/$fbname.golden"
  rm -f $tstfile > /dev/null
  python src/bsmx2stages.py -i $bsmx -o $tstfile | grep "==================================>"
  diff $tstfile $goldfile > /dev/null
  if [ "$?" != "0" ]; then
    echo "$fbname does not match"
    FAIL=1
  fi
done
echo ""
exit $FAIL
