#!/bin/bash

# Goes through all the the recipe in the recipe folder
# Runs the controller in quick mode
# Fails on first failing recipe

pushd recipe
for recipe in *; do
  echo ".......................$recipe"
  ../src/runthread.py -q -f $recipe
  if [ "$?" != "0" ] ; then
    echo "!!!!!!!!!! Tests Failed !!!!!!!!!!"
    exit 1
  fi
done
popd
echo "===========All Tests Passed================"
