#!/bin/bash

# Updates a computer with new software and start the runscan.py
# program in the background

# Kill any running version of runscan
pkill -9 runscan.py

# Update code
git pull
cd src/cgibin
sudo ./INSTALL
cd ..

# Restart runscan.py
./runscan.py -u $USER &> /dev/null & 