version: '3'
services:
  dynamodb:
    image: "amazon/dynamodb-local:1.20.0"
    command: "-jar DynamoDBLocal.jar -sharedDb"
  hopfront:
    build: 
        context: .
    ports:
      - "8080:8080"
    environment:
      FLASK_DEBUG: "true"
      PYTHONUNBUFFERED: 1
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      REGION: 'us-west-2'
    depends_on:
      - dynamodb
      - mosquitto
  mosquitto:
    build: 
        context: ./mosquitto
    ports:
      - 1883:1883
  onlinebeersmith:
    build:
        context: ../..
        dockerfile: src/onlinebeersmith/Dockerfile
    depends_on:
      - dynamodb
  prometheus:
    build:
        context: ./prometheus
    ports:
      - "9090:9090"
    depends_on:
      - hopfront
    volumes:
      - /var/tmp/prometheus:/prometheus
  grafana:
    build:
      context: ./grafana
    ports:
     - '3000:3000'
