version: '3'
services:
  dynamodb:
    image: "amazon/dynamodb-local:1.20.0"
    ports:
      - "8000:8000"
  brew:
    build: 
        context: .
    ports:
      - "8080:8080"
    environment:
      FLASK_DEBUG: "true"
      PYTHONUNBUFFERED: 1
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      REGION: 'us-west-2'
    depends_on:
      - dynamodb
