#!/bin/bash

# Script to install files into cgi-bin
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd $DIR
sudo cp ./*.py /usr/lib/cgi-bin
sudo chmod 755 /usr/lib/cgi-bin/*
sudo cp -p ../../datadir/* /tmp
chmod 666 /tmp/*.pkl
sudo cp -p ../html/*.html /var/www
chmod 755 /var/www/*.html
popd
