# syntax=docker/dockerfile:1
FROM python:3.7
WORKDIR /code
#RUN apk add --no-cache gcc musl-dev linux-headers
#RUN apt install --no-cache gcc glibc-dev linux-headers
RUN apt install  libffi-dev
RUN apt install  bash
RUN apt install  curl
#RUN apt install  jq
RUN pip install --upgrade pip
COPY . .
#RUN pip install -r onlinebeersmith/requirements.txt
CMD ["sleep", "infinity"]