#!/bin/bash
#
# Script to start the program for proper brewing
# with all the options
# 
# This scripts is hackish at this point. It should be cleaned up and most likely 
# moved into python
#
# Add proper logging for all print statements
# The stats should be send to a separate file from within python

usage() {
echo "USAGE: $0"

}

USR=$USER
SIMULATE=0
while getopts ":su:" opt; do
  case $opt in
    s)
      SIMULATE=1
      ;;
    u)
      USR=$OPTARG
      ;;
    \?)
      usage
      ;;
  esac
done
echo $SIMULATE

DATESTRING=`date +%F-%H-%M`
LOGFILE="brew-${DATESTRING}.log"
STATSFILE="stats-${DATESTRING}.log"

# Initial cleanup
pkill -9 -f logActual.py &> /dev/null
pkill -9 -f threadscan.py &> /dev/null

echo "Output log copied to ${LOGFILE}"
echo "Status, of all sensors and switches logged to ${STATSFILE}"
pushd hoplog
python logActual.py > /tmp/${STATSFILE} &
popd

if [ "$SIMULATE" == "1" ]; then
  sudo ./threadscan.py -u mikael | /usr/bin/tee /tmp/${LOGFILE}
else
  sudo ./threadscan.py -u mikael -e | /usr/bin/tee /tmp/${LOGFILE}
fi

pkill -9 -f logActual.py &> /dev/null
pkill -9 -f threadscan.py &> /dev/null

