#!/bin/bash
#
# Script to start the program for proper brewing
# with all the options
# 
# This scripts is hackish at this point. It should be cleaned up and most likely 
# moved into python
#
# Add proper logging for all print statements
# The stats should be send to a separate file from within python

usage() {
echo "USAGE: $0"

}

USR=$USER
SIMULATE=0
TYPEOFEQUIPMENT=
while getopts ":su:t:bh" opt; do
  case $opt in
    s)
      SIMULATE=1
      ;;
    u)
      USR=$OPTARG
      ;;
    t)
      TYPEOFEQUIPMENT=$OPTARG
      ;;
    b)
      TYPEOFEQUIPMENT='Grain 4.5G, 5Gcooler, 8GBE, platechiller'
      ;;
    h)
      TYPEOFEQUIPMENT='Grain 3G, HERMS, 5Gcooler, 5Gpot'
      ;;
    \?)
      usage
      ;;
  esac
done
echo $SIMULATE

DATESTRING=`date +%F-%H-%M`
LOGFILE="brew-${DATESTRING}.log"

# Start and stop  beersmith to get an updated Cloud.bsmx file
/usr/bin/beersmith2 &
sleep 20
xdotool windowactivate --sync $(xdotool search --name 'BeerSmith 2') key  --clearmodifiers --delay 100 alt+F4

# Initial cleanup
sudo pkill -9 -f threadscan.py &> /dev/null

echo "Output log copied to ${LOGFILE}"

if [ "$SIMULATE" == "1" ]; then
  sudo ./threadscan.py -u mikael 
else
  sudo ./threadscan.py -u mikael -e 
fi

#sudo pkill -9 -f threadscan.py &> /dev/null

