# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Show version
        run: echo 0

      - name: Show info
        run: |
          lsb_release -a
          pwd
          python --version
          whoami

      # Runs a set of commands using the runners shell
      - name: Install basic linux tools
        run: |
          sudo apt-get update
          sudo apt-get -y install g++ make
          sudo apt-get -y install unzip
          sudo apt-get -y install xdotool
          sudo apt-get -y install build-essential
          sudo apt-get -y install libusb-1.0-0-dev
          sudo apt-get -y install python3-virtualenv

      - name: Python packages
        run: |
          virtualenv venv
          source venv/bin/activate
          python --version
          pip install -r requirements.txt

      - name: Phidget
        run: |
          pushd phidget
          tar xvzf libphidget.tar.gz
          cd libphidget-*
          ./configure
          make
          sudo make install
          popd
          pushd phidget
          unzip PhidgetsPython.zip
          cd PhidgetsPython/
          sudo python setup.py install
          popd

      - name: Run tests
        run: |
          source venv/bin/activate
          source testequipmentname
          source testjson2stages

